ci: verify package count after building all

diff --git a/.github/workflows/update-repo-3party.yml b/.github/workflows/update-repo-3party.yml
--- a/.github/workflows/update-repo-3party.yml
+++ b/.github/workflows/update-repo-3party.yml
@@ -29,6 +29,18 @@ jobs:
         cd 3rdparty_pkgbuild
         ./auto-build.sh
 
+    - name: Verify package count
+      run: |
+        aur_package_count=$(cat ./3rdparty_pkgbuild/aur_packages | wc -l)
+        built_package_count=$(ls ../3rdparty-x86_64 | wc -l)
+
+        if [ $aur_package_count -ne $built_package_count ]; then
+          echo "ERROR: package counts do not match."
+          echo "Expected package count: $aur_package_count"
+          echo "Actual package count: $built_package_count"
+          exit 1
+        fi
+
     - name: List files
       run: |
         pwd
